### PR TITLE
feat: allow rescue/emergency boot with grub cmdline args

### PR DESCRIPTION
**Pull request by bsherman**
This uses a systemd-generator to dyamically write a drop-in config for the rescue and emergency services only when they are requested via the kernel cmdline, which requires console/grub access. This allows use of these modes with the default Fedora state of a password locked root user, but does not auto-allow root access in the case of a failed fsck-check, which can also drop into the emergency shell.

Relates: #470

### CODE REVIEW

**Comment by bsherman** [comment]
@ublue-os/approver please do NOT merge this until we've collected feedback. :-) Thank you.

**Comment by cgwalters** [comment]
Looks sane to me.  Arguably we could try to put this in systemd upstream too.

**Comment by bsherman** [comment]
> Looks sane to me. Arguably we could try to put this in systemd upstream too.

I'm not sure how easy it is to get merged into different projects. At the least, I figured we'd include it here and I'll PR to CoreOS.

Then we'd have running use cases before pushing further upstream.

**Review by KyleGospo — APPROVED** [review]
Tested well on my end!

**Comment by TriMoon** [comment]
Not to be nit-picking but....
Title should be "kernel" instead of "grub", as it is not specific to Grub...

**Review by TriMoon — COMMENTED** [review]
Not to be nit-picking but....
Title should be "kernel" instead of "grub", as it is not specific to Grub...

Plus it will boot, i guess, in a root shell?
_(So mention that also)_

**Review by EyeCantCU — APPROVED** [review]
Works over here as well :)

**Comment by bsherman** [comment]
> Arguably we could try to put this in systemd upstream too.

@cgwalters , I had planned to PR this into CoreOS as a replacement for the current static drop-ins. Would prefer I first attempt going upstream to systemd?

**Comment by cgwalters** [comment]
Landing in FCOS first sounds totally sane to me.

**Pull request merged**
