### PR TITLE
feat: Add xone and xpad-noone drivers

### PR DESCRIPTION
**Pull request by KyleGospo**

### CODE REVIEW

**Review by fiftydinar — COMMENTED** [review]
Wait, you should not remove xpadneo as you will cut Bluetooth Xbox One gamepad support than.

We should combine all 3 of these: xpadneo, xone & xpad-noone

**Comment by KyleGospo** [comment]
@bsherman @castrojo Needs real-world testing, modules build/mages look good.

**Comment by KyleGospo** [comment]
> Wait, you should not remove xpadneo as you will cut Bluetooth Xbox One gamepad support than.
> 
> We should combine all 3 of these: xpadneo, xone & xpad-noone

Does xpadneo not conflict with xone/xpad?

**Comment by fiftydinar** [comment]
> > Wait, you should not remove xpadneo as you will cut Bluetooth Xbox One gamepad support than.
> > We should combine all 3 of these: xpadneo, xone & xpad-noone
> 
> Does xpadneo not conflict with xone/xpad?

Xone conflicted with xpad before, now it doesn't since you added xpad-noone

Xpadneo had no issues

I don't have those gamepads to test, I'm just looking at their github. Only xpadneo covers Bluetooth Xbox One gamepads as far as I see.

**Comment by KyleGospo** [comment]
> > > Wait, you should not remove xpadneo as you will cut Bluetooth Xbox One gamepad support than.
> > > We should combine all 3 of these: xpadneo, xone & xpad-noone
> > 
> > 
> > Does xpadneo not conflict with xone/xpad?
> 
> Xone conflicted with xpad before, now it doesn't since you added xpad-noone
> 
> Xpadneo had no issues
> 
> I don't have those gamepads to test, I'm just looking at their github. Only xpadneo covers Bluetooth Xbox One gamepads as far as I see.

It's restored now

**Review by bsherman — APPROVED** [review]
This looks great! I can test anytime... I'm willing to merge first and test on an official build if others are.

**Comment by castrojo** [comment]
+1 to that, let's try it.

**Comment by bsherman** [comment]
I'll be testing on my AMD machine so I can test as soon as this `main` repo `main` branch build completes :-)

**Comment by throwaway43** [comment]
Unfortunately I have not been able to get my xbox one controller working (wired). As advised, I made sure to install the latest drivers on Windows (through [Xbox-Accessories](https://apps.microsoft.com/store/detail/xbox-accessories/9NBLGGH30XJ3)) I even went so far as to reinstall it entirely in hopes of resolving the issue, but alas. Even rebasing from my custom image (through startingpoint) to silverblue-main, bazzite and bluefin didn't resolve this for me. Eventually, I got somewhat desperate and decided to brute-force it. The following has finally resolved it for me, but it's far from an elegant solution:
1. Fork [ublue-os/main](https://github.com/ublue-os/main)
2.  Remove the following lines in [main-install.sh](https://github.com/ublue-os/main/blob/main/main-install.sh):
    /tmp/akmods-rpms/kmods/*xpadneo*.rpm \
    /tmp/akmods-rpms/kmods/*xone*.rpm \
    /tmp/akmods-rpms/kmods/*xpad-noone*.rpm
3. (After ensuring the actions work again and even customize it so that it only creates the one image I use (silverblue-main).) Make changes to Containerfile and recipe.yml to change the base image to your forked one.

I tried simply uninstalling xone etc on my device, but to no avail. That's why I *succumbed* to the aforementioned inelegant solution. I'm sure a far more elegant solution exists. But this is my *workaround* till then :sweat_smile:.

**Comment by bsherman** [comment]
> Unfortunately, I have not been able to get my xbox one controller working (wired) since this has been merged. As prescribed, I made sure to install the latest drivers on Windows (through [Xbox-Accessories](https://apps.microsoft.com/store/detail/xbox-accessories/9NBLGGH30XJ3)). I even went so far as to reinstall Silverblue entirely in hopes of remedying the issue, but alas.

That IS frustrating, so thank you for coming back to report your workaround.

Did you ever get any logs about the problem? Running `dmesg -T -w` in a terminal, then plugging in the controller should show what's happening.

Without logs the primary culprit I would expect here is SecureBoot enabled on an AMD machine which didn't otherwise require loading the universal blue MOK with `just enroll-secure-boot-key`.

**Comment by throwaway43** [comment]
> Running `dmesg -T -w` in a terminal, then plugging in the controller should show what's happening.

[Sun Sep  3 17:51:19 2023] usb 1-2: new full-speed USB device number 6 using xhci_hcd
[Sun Sep  3 17:51:20 2023] usb 1-2: New USB device found, idVendor=045e, idProduct=02ea, bcdDevice= 5.11
[Sun Sep  3 17:51:20 2023] usb 1-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[Sun Sep  3 17:51:20 2023] usb 1-2: Product: Controller
[Sun Sep  3 17:51:20 2023] usb 1-2: Manufacturer: Microsoft
[Sun Sep  3 17:51:20 2023] usb 1-2: SerialNumber: 3032363030353438393736363234
[Sun Sep  3 17:51:20 2023] Loading of module with unavailable key is rejected

> Without logs the primary culprit I would expect here is SecureBoot enabled on an AMD machine which didn't otherwise require loading the universal blue MOK with `just enroll-secure-boot-key`.

Bullseye :clap: ! Thank you for your input! Much appreciated! I'll revert my image back to how it used to be :smile:  ! As the kernel modules are enabled by default, is it perhaps worthwhile to mention the importance of the `just enroll-secure-boot-key` command more prominently?

**Pull request merged**
