### PR TITLE
feat: add setroubleshoot and setools

### PR DESCRIPTION
**Pull request by qoijjj**
https://github.com/ublue-os/main/issues/465

### CODE REVIEW

**Review by KyleGospo — APPROVED** [review]
Previously approved & then reverted due to issue fixed in this PR. Thank you! Re-approved.

**Comment by castrojo** [comment]
What causes the notification spam? Is it because of other things in bazzite or would it affect the base images?

**Comment by qoijjj** [comment]
@castrojo I'm testing on a base image and it's very spammy.

**Comment by qoijjj** [comment]
It's just the nature of selinux. It blocks a lot of things that don't actually impact usability

**Comment by qoijjj** [comment]
For example, when i started chromium to write this, a bunch of selinux alerts popped up, but nothing actually breaks :smile:

**Comment by qoijjj** [comment]
Also, this just changes the default, the user can still override it using the config gui tool to re-enable alerts.

**Comment by qoijjj** [comment]
closing out old PRs

**Pull request closed without merging**
