### PR TITLE
chore(iso): added KS and ISO generation

### PR DESCRIPTION
**Pull request by bigpod98**

### CODE REVIEW

**Review by castrojo — APPROVED** [review]

**Comment by castrojo** [comment]
For other reviewers, here's the output: https://github.com/bigpod98/main/releases/tag/v1.0.4

**Review by castrojo — APPROVED** [review]

**Review by castrojo — APPROVED** [review]

**Comment by lamarios** [comment]
How to trigger this one ? I maintain my own fork of ublue-os and wish to generate my ISO, I modified my yml accordingly (image names/ repos etc...) but it gets skipped on push build. I tried to create a new release but that did not trigger it either.

**Comment by castrojo** [comment]
The action in my bluefin repo is simplified which might be useful: https://github.com/ublue-os/bluefin/blob/main/.github/workflows/release-please.yml

Would you mind posting in the [discussion forum](https://github.com/orgs/ublue-os/discussions)? This stuff is pretty fresh and it's mostly undocumented, I'd love to at least capture that so we can start to document this for the next person. 

Link us up to your repo and I'd be happy to take a look, thanks for playing with this, this is the kind of thing we need to help document it for the next person!

**Comment by lamarios** [comment]
[done](https://github.com/orgs/ublue-os/discussions/126)

I'm not just playing with it :) all my machines are running this. This project is great ! Can't wait for the yafti integration.

**Pull request merged**
