### PR TITLE
chore(ci): Bump isogenerator to v2.1.0

### PR DESCRIPTION
**Pull request by EyeCantCU**
This bumps isogenerator to v2.1.0

### CODE REVIEW

**Review by KyleGospo — APPROVED** [review]

**Comment by castrojo** [comment]
Please revert, we do this on purpose, I can explain when I'm not on mobile

**Comment by castrojo** [comment]
Or rather, pin the explicit version!

**Comment by EyeCantCU** [comment]
All right. I'll fix this up

**Comment by castrojo** [comment]
For some context, this is so when if someone is revving on the isogenerator to test in other images we can always ensure that main/nvidia are releaseable on a known-good version. 

Then we explicitly bump after testing. Thanks!

**Review by KyleGospo — APPROVED** [review]

**Comment by EyeCantCU** [comment]
That makes a lot of sense. Thank you for explaining that to me. Wouldn't want to ship a bad ISO

**Pull request merged**
