### PR TITLE
post-install: Enable Fstrim.timer systemctl service

### PR DESCRIPTION
**Pull request by EliasOfWaffle**

### CODE REVIEW

**Comment by KyleGospo** [comment]
This should already be enabled upstream.

**Comment by EliasOfWaffle** [comment]
> This should already be enabled upstream.

for some reason i have to enabled in my pc, can be necessary to view if is really enabled as default using "sudo systemctl status fstrim.timer"

**Comment by KyleGospo** [comment]
https://fedoraproject.org/wiki/Changes/EnableFSTrimTimer

Enabled in Fedora 32

**Comment by EliasOfWaffle** [comment]
> https://fedoraproject.org/wiki/Changes/EnableFSTrimTimer
> 
> Enabled in Fedora 32, also enabled in a new VM.

oh thanks, in this case my fedora 39 beta can be a bug ? i think that a can be make a confusion about, thanks.
In this case i will close this PR, sorry for my mistake

**Pull request closed without merging**
